image: python:3.8

run:
  script:
    # export a few variables based on the current branch
    - chmod +x set_env_vars_based_on_git_branch.sh
    - source ./set_env_vars_based_on_git_branch.sh
    # check that the exports were correct
    - echo $DEPLOY_SERVER_NAME
    - echo $PRIVKEY_FILE
    # install ansible for provisioning of server (setup db, nginx, MTA...)
    - echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - apt-get update -y
    - apt-get install -y ansible
    - cp ansible/ansible.cfg ~/.ansible.cfg
    - ansible-galaxy install --roles-path ansible/roles anxs.postgresql,v1.11.1
    - eval "$(ssh-agent -s)" #start the ssh agent
    - openssl aes-256-cbc -K $encrypted_e64c44062370_key -iv $encrypted_e64c44062370_iv -in ssh-privkeys.tar.enc -out ssh-privkeys.tar -d
    - tar xvf ssh-privkeys.tar
    - chmod 600 $PRIVKEY_FILE
    - ssh-add $PRIVKEY_FILE
    # ansible cannot get the vault password from an env var
    - echo $ANSIBLE_VAULT_PASSWORD > /tmp/.ansible_vault_pwd
    - export ANSIBLE_VAULT_PASSWORD_FILE=/tmp/.ansible_vault_pwd
    - ansible-playbook -i ansible/ansible_inventory ansible/site.yml --limit $DEPLOY_SERVER_NAME
