---
dependencies:
  - role: anxs.postgresql
    become: yes
    postgresql_version: 9.6
    postgresql_users:
      - name: "{{ db_user_name }}"
        pass: "{{ db_user_password }}"
        encrypted: yes
    postgresql_listen_addresses:
      - "*"
    # WAL settings for wal-g backup
    postgresql_wal_level: "replica"
    postgresql_archive_mode: "{{ db_backup_archive_mode }}"
    postgresql_archive_timeout: 120
    postgresql_archive_command: "{{ db_backup_archive_command }}"
  - role: rvm.ruby
    # install ruby 2.5.3 via rvm as ubuntu 18.04 only has 2.5.1
    # we need 2.5.3 to fix a bug that breaks the pop poller daemon
    become: yes
    rvm1_rubies: ['ruby-2.5.3']
    rvm1_rvm_check_for_updates: False
